[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
godot-rust-script = { workspace = true, features = ["scripts"] }
backtrace = "0.3.64"
num_enum = "0.7.1"
