extends Object

enum BuildingIds {
	ROAD_LEFT_RIGHT = 0x1D,
	ROAD_TOP_BOTTOM = 0x1E,
}

const networks := {
	# Powerlines
	0x0E: "res://resources/Objects/Networks/Powerline/left_right.tscn",
	0x0F: "res://resources/Objects/Networks/Powerline/top_bottom.tscn",
	0x10: "res://resources/Objects/Networks/Powerline/high_top_bottom.tscn",
	0x11: "res://resources/Objects/Networks/Powerline/left_high_right.tscn",
	0x12: "res://resources/Objects/Networks/Powerline/top_high_bottom.tscn",
	0x13: "res://resources/Objects/Networks/Powerline/high_left_right.tscn",
	0x14: "res://resources/Objects/Networks/Powerline/bottom_right.tscn",
	0x15: "res://resources/Objects/Networks/Powerline/bottom_left.tscn",
	0x16: "res://resources/Objects/Networks/Powerline/top_left.tscn",
	0x17: "res://resources/Objects/Networks/Powerline/top_right.tscn",
	0x18: "res://resources/Objects/Networks/Powerline/right_top_bottom.tscn",
	0x19: "res://resources/Objects/Networks/Powerline/left_bottom_right.tscn",
	0x1A: "res://resources/Objects/Networks/Powerline/top_left_bottom.tscn",
	0x1B: "res://resources/Objects/Networks/Powerline/left_top_right.tscn",
	0x1C: "res://resources/Objects/Networks/Powerline/left_top_bottom_right.tscn",
	0x5C: "res://resources/Objects/Networks/Powerline/bridge_top_bottom.tscn",

	# Road
	0x1D: "res://resources/Objects/Networks/Road/left_right.tscn",
	0x1E: "res://resources/Objects/Networks/Road/top_bottom.tscn",
	0x1F: "res://resources/Objects/Networks/Road/high_top_bottom.tscn",
	0x20: "res://resources/Objects/Networks/Road/left_high_right.tscn",
	0x21: "res://resources/Objects/Networks/Road/top_high_bottom.tscn",
	0x22: "res://resources/Objects/Networks/Road/high_left_right.tscn",
	0x23: "res://resources/Objects/Networks/Road/top_right.tscn",
	0x24: "res://resources/Objects/Networks/Road/bottom_right.tscn",
	0x25: "res://resources/Objects/Networks/Road/bottom_left.tscn",
	0x26: "res://resources/Objects/Networks/Road/top_left.tscn",
	0x27: "res://resources/Objects/Networks/Road/right_top_bottom.tscn",
	0x28: "res://resources/Objects/Networks/Road/left_bottom_right.tscn",
	0x29: "res://resources/Objects/Networks/Road/top_left_bottom.tscn",
	0x2A: "res://resources/Objects/Networks/Road/left_top_right.tscn",
	0x2B: "res://resources/Objects/Networks/Road/left_top_bottom_right.tscn",
	0x43: "res://resources/Objects/Networks/Road/left_right_power_top_bottom.tscn",
	0x44: "res://resources/Objects/Networks/Road/top_bottom_power_left_right.tscn",

	# Suspension Bridge
	0x51: "res://resources/Objects/Networks/Bridge/bridge_suspension_start_bottom.tscn",
	0x52: "res://resources/Objects/Networks/Bridge/bridge_suspension_middle_bottom.tscn",
	0x53: "res://resources/Objects/Networks/Bridge/bridge_suspension_center.tscn",
	0x54: "res://resources/Objects/Networks/Bridge/bridge_suspension_middle_top.tscn",
	0x55: "res://resources/Objects/Networks/Bridge/bridge_suspension_end_top.tscn",

	# Pylon Bridge
	0x56: "res://resources/Objects/Networks/Bridge/bridge_raising_tower_top_bottom.tscn",
	0x57: "res://resources/Objects/Networks/Bridge/bridge_top.tscn",
	0x58: "res://resources/Objects/Networks/Bridge/bridge_top.tscn",
}

const buildings = {
	0x0D: "res://resources/Objects/Buildings/park_small.tscn",
	0x06: "res://resources/Objects/Buildings/tree_single.tscn",
	0x73: "res://resources/Objects/Buildings/home_middle_class_1.tscn",
	0x74: "res://resources/Objects/Buildings/home_middle_class_2.tscn",
	0x75: "res://resources/Objects/Buildings/home_middle_class_3.tscn",
	0x76: "res://resources/Objects/Buildings/home_middle_class_4.tscn",
	0x77: "res://resources/Objects/Buildings/home_middle_class_5.tscn",
	0xF7: "res://resources/Objects/Buildings/church.tscn",
	0x96: "res://resources/Objects/Buildings/office_building_medium_1.tscn",
	0x98: "res://resources/Objects/Buildings/office_building_medium_2.tscn",
	0x9A: "res://resources/Objects/Buildings/office_building_medium_3.tscn",
	0x9B: "res://resources/Objects/Buildings/office_building_medium_4.tscn",
	0x9C: "res://resources/Objects/Buildings/office_building_medium_5.tscn",
	0x9D: "res://resources/Objects/Buildings/office_building_medium_6.tscn",
	0x8A: "res://resources/Objects/Buildings/abandoned_building_1.tscn",
	0x8B: "res://resources/Objects/Buildings/abandoned_building_2.tscn",
	0xAA: "res://resources/Objects/Buildings/abandoned_building_3.tscn",
	0xAB: "res://resources/Objects/Buildings/abandoned_building_4.tscn",
	0xAC: "res://resources/Objects/Buildings/abandoned_building_5.tscn",
	0xAD: "res://resources/Objects/Buildings/abandoned_building_6.tscn",
	0x78: "res://resources/Objects/Buildings/home_upper_class_1.tscn",
	0x79: "res://resources/Objects/Buildings/home_upper_class_2.tscn",
	0x7A: "res://resources/Objects/Buildings/home_upper_class_3.tscn",
	0x7B: "res://resources/Objects/Buildings/home_upper_class_4.tscn",
	0xE6: "res://resources/Objects/Ground/tarmac.tscn",
	0xEA: "res://resources/Objects/Buildings/tarmac_radar.tscn",
	0xC2: "res://resources/Objects/Buildings/construction_1-2.tscn",
	0xC3: "res://resources/Objects/Buildings/construction_1-2.tscn",
	0xA6: "res://resources/Objects/Buildings/construction_3.tscn",
	0xA7: "res://resources/Objects/Buildings/construction_4.tscn",
	0xA8: "res://resources/Objects/Buildings/construction_5.tscn",
	0xA9: "res://resources/Objects/Buildings/construction_6.tscn",
	0x88: "res://resources/Objects/Buildings/construction_7.tscn",
	0x89: "res://resources/Objects/Buildings/construction_8.tscn",
	0xE3: "res://resources/Objects/Buildings/airport_warehouse.tscn",
	0xE4: "res://resources/Objects/Buildings/airport_building_1.tscn",
	0xE5: "res://resources/Objects/Buildings/airport_building_2.tscn",
	0xE8: "res://resources/Objects/Buildings/airport_hangar_1.tscn",
	0xDD: "res://resources/Objects/Buildings/airport_runway.tscn",
	0xDF: "res://resources/Objects/Buildings/airport_runway_intersection.tscn",
	0xF6: "res://resources/Objects/Buildings/hangar_2.tscn",
	0x91: "res://resources/Objects/Buildings/condominiums_medium_1.tscn",
	0x92: "res://resources/Objects/Buildings/condominiums_medium_2.tscn",
	0x93: "res://resources/Objects/Buildings/condominiums_medium_3.tscn",
	0xB0: "res://resources/Objects/Buildings/condominiums_large_1.tscn",
	0xB1: "res://resources/Objects/Buildings/condominiums_large_2.tscn",
	0xA0: "res://resources/Objects/Buildings/factory_small_1.tscn",
	0xA1: "res://resources/Objects/Buildings/factory_small_2.tscn",
	0xA2: "res://resources/Objects/Buildings/factory_small_3.tscn",
	0xA3: "res://resources/Objects/Buildings/factory_small_4.tscn",
	0xA4: "res://resources/Objects/Buildings/factory_small_5.tscn",
	0xA5: "res://resources/Objects/Buildings/factory_small_6.tscn",
	0xD2: "res://resources/Objects/Buildings/station_police.tscn",
	0x8F: "res://resources/Objects/Buildings/apartments_medium_1.tscn",
	0x90: "res://resources/Objects/Buildings/apartments_medium_2.tscn",
	0x83: "res://resources/Objects/Buildings/toy_store.tscn",
	0x87: "res://resources/Objects/Buildings/industrial_substation.tscn",
	0x80: "res://resources/Objects/Buildings/offices_small_1.tscn",
	0x81: "res://resources/Objects/Buildings/offices_small_2.tscn",
	0xBA: "res://resources/Objects/Buildings/offices_historic.tscn",
	0xDC: "res://resources/Objects/Buildings/water_pump.tscn",
	0xD1: "res://resources/Objects/Buildings/station_hospital.tscn",
	0x7E: "res://resources/Objects/Buildings/convenience_store.tscn",
	0x7C: "res://resources/Objects/Buildings/station_gas_1.tscn",
	0x7F: "res://resources/Objects/Buildings/station_gas_2.tscn",
	0x70: "res://resources/Objects/Buildings/home_lower_class_1.tscn",
	0x71: "res://resources/Objects/Buildings/home_lower_class_2.tscn",
	0x72: "res://resources/Objects/Buildings/home_lower_class_3.tscn",
	0x82: "res://resources/Objects/Buildings/warehouse.tscn",
	0xE1: "res://resources/Objects/Buildings/airport_civilian_control_tower.tscn",
	0xD3: "res://resources/Objects/Buildings/station_fire.tscn",
	0xCD: "res://resources/Objects/Buildings/powerplant_microwave.tscn",
	0x97: "res://resources/Objects/Buildings/resort_hotel.tscn",
	0xAE: "res://resources/Objects/Buildings/apartments_large_1.tscn",
	0xAF: "res://resources/Objects/Buildings/apartments_large_2.tscn",
	0x8C: "res://resources/Objects/Buildings/apartments_small_1.tscn",
	0x8D: "res://resources/Objects/Buildings/apartments_small_2.tscn",
	0x8E: "res://resources/Objects/Buildings/apartments_small_3.tscn",
	0x07: "res://resources/Objects/Buildings/tree_couple.tscn",
	0x85: "res://resources/Objects/Buildings/chemical_storage.tscn",
	0xBC: "res://resources/Objects/Buildings/chemical_processing_1.tscn",
	0x9F: "res://resources/Objects/Buildings/chemical_processing_2.tscn",
	0xD6: "res://resources/Objects/Buildings/school.tscn",
	0xF5: "res://resources/Objects/Buildings/library.tscn",
	0xF8: "res://resources/Objects/Buildings/marina.tscn",
	0xC0: "res://resources/Objects/Buildings/warehouse_large_1.tscn",
	0xC1: "res://resources/Objects/Buildings/warehouse_large_2.tscn",
	0x84: "res://resources/Objects/Buildings/warehouse_small_1.tscn",
	0x86: "res://resources/Objects/Buildings/warehouse_small_2.tscn",
	0x9E: "res://resources/Objects/Buildings/warehouse_medium.tscn",
	0x7D: "res://resources/Objects/Buildings/bb_inn.tscn",
	0xD9: "res://resources/Objects/Buildings/college.tscn",
	0xFB: "res://resources/Objects/Buildings/arcology_plymouth.tscn",
	0xFC: "res://resources/Objects/Buildings/arcology_forest.tscn",
	0xFD: "res://resources/Objects/Buildings/arcology_darco.tscn",
	0xFE: "res://resources/Objects/Buildings/arcology_launch.tscn",
	0xF3: "res://resources/Objects/Buildings/mayors_house.tscn",
	0xD4: "res://resources/Objects/Buildings/museum.tscn",
	0x99: "res://resources/Objects/Buildings/office_retail.tscn",
	0xB9: "res://resources/Objects/Buildings/parking_lot.tscn",
	0x94: "res://resources/Objects/Buildings/shopping_centre.tscn",
	0xB5: "res://resources/Objects/Buildings/theatre.tscn",
	0xF4: "res://resources/Objects/Buildings/water_treatment.tscn",
}

static func _load(index: Dictionary, object_id: int) -> PackedScene:
	assert(object_id in index, "0x%x is not a vaild object id" % object_id)
	assert(ResourceLoader.exists(index[object_id], "PackedScene"), "\"%s\" is not a PackedScene" % index[object_id])

	return ResourceLoader.load(index[object_id]) as PackedScene

static func load_network(object_id) -> PackedScene:
	return _load(networks, object_id)


static func load_building(object_id) -> PackedScene:
	return _load(buildings, object_id)
