###
# Copyright (c) SimChopper; Jovan Gerodetti and contributors.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
###

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build.yml

  rust-clippy:
    runs-on: 'ubuntu-22.04'

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./native/
      - name: Check
        run: |
          cd native/
          cargo clippy -- -D warnings

  licenses:
    runs-on: 'ubuntu-22.04'

    steps:
      - name: checkout
        uses: actions/checkout@v5
      - uses: hustcer/setup-nu@main
        with:
          version: "0.111.*"
      - name: MPL Check
        shell: nu {0}
        run: |
          ./scripts/license_header.nu
          if (git diff | length) == 0 { exit 0 } else { exit 1 } 
